version: "3.9"

services:
  nest:
    build: .
    ports:
      - "3000" 
    volumes:
      - .:/app
    working_dir: /app
    command: pnpm start:dev 
    env_file:
      - .env.${NODE_ENV:-dev} 
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwer1234
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s  
    networks:
      - backend
    ports:
      - "3306:3306"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      nest:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # Nginx를 호스트 8080 포트로 노출
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
